services:
  tasklist:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "127.0.0.1:58080:8080"

  tasklist-unit-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: unit-test
    ports:
      - "127.0.0.1:58080:8080"